name: MyFirstWorkFlow
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' 
jobs:
  demo:
    runs-on: windows-latest
    steps:
    - name: windowstwo
      shell: pwsh
      run: get-computerinfo
