name: testworkflow
on:
    push:
jobs:
    job1:
        name: testing
        runs-on: ubuntu-latest
        steps:
            - name: createdir
              run: mkdir ./artifacts
            - name: listfile
              run: |
                echo 'ls -lrt' >> ./artifacts/list.txt
                echo 'hostname' >> ./artifacts/hostname.txt
            - name: uploadfile
              uses: actions/upload-artifact@v7.0.1
              with:
                name: directories
                path: |
                    ./artifacts/list.txt
                    ./artifacts/hostname.txt
